import duckdb
import pandas as pd
from google.cloud import bigquery
import os

# Configuration based on the DBT profiles.yml
PROJECT_ID = 'ntu-project-489202'
DATASET_ID = 'london_bicycle'
DUCKDB_PATH = './data/london_bicycle.duckdb'

# Define the models (fact and dim tables) to extract
TABLES_TO_EXTRACT = [
    'dim_station',
    'dim_duration_by_mth',
    'fact_hires'
]

def extract_and_load():
    """
    Connects to BigQuery to extract the tables generated by DBT
    and saves them to a local DuckDB file.
    """
    print(f"--- EXTRACT FROM BIGQUERY ({PROJECT_ID}.{DATASET_ID}) TO DUCKDB ({DUCKDB_PATH}) ---")
    
    # Initialize BigQuery client
    # Note: Requires google-cloud-bigquery installed and proper authentication
    # (e.g. `gcloud auth application-default login`)
    try:
        bq_client = bigquery.Client(project=PROJECT_ID)
    except Exception as e:
        print(f"Error initializing BigQuery client: {e}")
        print("Please ensure you are authenticated using `gcloud auth application-default login`.")
        return

    # Connect to local DuckDB database
    con = duckdb.connect(DUCKDB_PATH)
    
    for table_name in TABLES_TO_EXTRACT:
        print(f"\nProcessing table: {table_name}")
        
        # 1. Query table from BigQuery
        query = f"SELECT * FROM `{PROJECT_ID}.{DATASET_ID}.{table_name}`"
        
        try:
            print("  Downloading from BigQuery...")
            # to_dataframe() will convert the results directly into a pandas DataFrame
            # Requires pandas-gbq or db-dtypes for optimal conversion
            df = bq_client.query(query).to_dataframe()
            print(f"  Downloaded {len(df)} rows.")
            
            # 2. Write table to DuckDB
            print("  Loading into DuckDB...")
            # Using duckdb's ability to directly query a local pandas dataframe
            con.execute(f"CREATE OR REPLACE TABLE {table_name} AS SELECT * FROM df")
            print(f"  Successfully saved `{table_name}` to DuckDB.")
            
        except Exception as e:
            print(f"  Error processing {table_name}: {e}")

    con.close()
    print("\n--- ALL TASKS COMPLETED ---")

if __name__ == "__main__":
    extract_and_load()
