cloud_london_bicycles:
  outputs:
    dev:
      dataset: london_bicycles
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: EU
      method: oauth
      priority: interactive
      project: testgcp-487607
      threads: 1
      type: bigquery
  target: dev